### PR TITLE
Add duration Mixpanel property

### PR DESCRIPTION
**Pull request by dhritzkiv**
Duration is a property for tracking how long an event took. It appears in the mixpanel interface as a mixpanel property. I don't believe it's used for Engage messages.

### CODE REVIEW

**Comment by eealeivan** [comment]
Hi,

Do you know if there is any documentation for this property? What type should be used etc.

**Comment by dhritzkiv** [comment]
The documentation is pretty scattered among the iOS, Android, and JavaScript projects:

[JavaScript](https://mixpanel.com/help/reference/javascript-full-api-reference#mixpanel.time_event)
[iOS (Swift](https://mixpanel.com/help/reference/swift#event-timing)
[Android](https://mixpanel.com/help/reference/android#event_timing)

The data type is not defined, but it's some sort of numerical value representing seconds. I've been using `double`, and it's been fine.

**Comment by eealeivan** [comment]
Can you please provide an example of raw json message?

**Comment by dhritzkiv** [comment]
I can give you the class field that i’m currently using to achieve it.

In a class marked with`[DataContract]`, I have this field:

```csharp
[DataMember(Name = "$duration")]
public double Duration { get; private set; }
```

Which presumably serializes the data to JSON like

```json
"$duration": 5.6192
```

**Comment by dhritzkiv** [comment]
(I’m away from my PC for the weekend, so I can’t inspect the traffic presently)

**Comment by dhritzkiv** [comment]
Here is an example of the raw json:

```json
{
    "event": "AppClose",
    "properties": {
        "token": "REDACTED",
        "distinct_id": "ea2930c7-89bd-4366-be8f-4e4dd762bd10",
        "$app_version": "1.1.0",
        "$os": "Windows",
        "$os_version": "10.0.17134",
        "$screen_height": 1440,
        "$screen_width": 2560,
        "$duration": 20.4563757
    }
}
```

**Comment by eealeivan** [comment]
$duration property is now supported in v5.0.0

**Pull request closed without merging**
